"""V006_exams_training_audit

Revision ID: 6149a616cfc9
Revises: b461e824b542
Create Date: 2026-03-10 03:53:48.888140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6149a616cfc9'
down_revision: Union[str, None] = 'b461e824b542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_jobs',
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('biz_type', sa.String(length=64), nullable=True),
    sa.Column('biz_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_job_type'), 'async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_async_jobs_status'), 'async_jobs', ['status'], unique=False)
    op.create_table('exam_papers',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('paper_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('exams',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_mode', sa.String(length=32), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('pass_result', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_status'), 'exam_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_table('exam_paper_items',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_paper_items_paper_id'), 'exam_paper_items', ['paper_id'], unique=False)
    op.create_table('exam_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_answers_attempt_id'), 'exam_answers', ['attempt_id'], unique=False)
    op.create_table('training_tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_version_id', sa.UUID(), nullable=True),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_makeup_exam', sa.Boolean(), nullable=False),
    sa.Column('makeup_exam_limit', sa.Integer(), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_tasks_status'), 'training_tasks', ['status'], unique=False)
    op.create_table('training_assignments',
    sa.Column('training_task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_status', sa.String(length=32), nullable=False),
    sa.Column('study_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exam_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_task_id'], ['training_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_assignments_training_task_id'), 'training_assignments', ['training_task_id'], unique=False)
    op.create_index(op.f('ix_training_assignments_user_id'), 'training_assignments', ['user_id'], unique=False)
    op.create_table('study_progress',
    sa.Column('training_assignment_id', sa.UUID(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('last_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['training_assignment_id'], ['training_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_progress')
    op.drop_index(op.f('ix_training_assignments_user_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_training_task_id'), table_name='training_assignments')
    op.drop_table('training_assignments')
    op.drop_index(op.f('ix_training_tasks_status'), table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_exam_answers_attempt_id'), table_name='exam_answers')
    op.drop_table('exam_answers')
    op.drop_index(op.f('ix_exam_paper_items_paper_id'), table_name='exam_paper_items')
    op.drop_table('exam_paper_items')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_status'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_async_jobs_status'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_job_type'), table_name='async_jobs')
    op.drop_table('async_jobs')
    # ### end Alembic commands ###
