"""add_node_type_source_type

Revision ID: 6e22c463cc8a
Revises: 7015173c201a
Create Date: 2026-03-14 14:58:39.240709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e22c463cc8a'
down_revision: Union[str, None] = '7015173c201a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_point_candidates', sa.Column('source_type', sa.String(length=32), nullable=False, server_default='document'))
    op.create_index(op.f('ix_knowledge_point_candidates_source_type'), 'knowledge_point_candidates', ['source_type'], unique=False)
    op.add_column('knowledge_points', sa.Column('node_type', sa.String(length=32), nullable=False, server_default='knowledge_point'))
    op.create_index(op.f('ix_knowledge_points_node_type'), 'knowledge_points', ['node_type'], unique=False)

    # Data migration: set node_type for existing nodes
    # Nodes that have children (are parent of other nodes) -> category
    op.execute("""
        UPDATE knowledge_points SET node_type = 'category'
        WHERE id IN (SELECT DISTINCT parent_id FROM knowledge_points WHERE parent_id IS NOT NULL)
    """)
    # Set source_type for existing candidates based on document_chunk_id
    op.execute("""
        UPDATE knowledge_point_candidates SET source_type = 'document' WHERE document_chunk_id IS NOT NULL
    """)
    op.execute("""
        UPDATE knowledge_point_candidates SET source_type = 'manual' WHERE document_chunk_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_points_node_type'), table_name='knowledge_points')
    op.drop_column('knowledge_points', 'node_type')
    op.drop_index(op.f('ix_knowledge_point_candidates_source_type'), table_name='knowledge_point_candidates')
    op.drop_column('knowledge_point_candidates', 'source_type')
    # ### end Alembic commands ###
