"""add_source_candidate_id_to_knowledge_points

Revision ID: 7015173c201a
Revises: 6149a616cfc9
Create Date: 2026-03-14 14:20:04.010522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7015173c201a'
down_revision: Union[str, None] = '6149a616cfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_points', sa.Column('source_candidate_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_knowledge_points_source_candidate_id'), 'knowledge_points', ['source_candidate_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_points', 'knowledge_point_candidates', ['source_candidate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_points', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_points_source_candidate_id'), table_name='knowledge_points')
    op.drop_column('knowledge_points', 'source_candidate_id')
    # ### end Alembic commands ###
