"""V005_questions

Revision ID: b461e824b542
Revises: 4bc9e2a94e91
Create Date: 2026-03-10 03:48:09.959521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b461e824b542'
down_revision: Union[str, None] = '4bc9e2a94e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_generation_tasks',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_generation_tasks_status'), 'question_generation_tasks', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_table('question_versions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_versions_status'), 'question_versions', ['status'], unique=False)
    op.create_table('review_tasks',
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('review_stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_table('review_comments',
    sa.Column('review_task_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('comment_type', sa.String(length=32), nullable=False),
    sa.Column('target_path', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action_suggestion', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_review_task_id'), 'review_comments', ['review_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_review_task_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_question_versions_status'), table_name='question_versions')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_generation_tasks_status'), table_name='question_generation_tasks')
    op.drop_table('question_generation_tasks')
    # ### end Alembic commands ###
