"""V003_knowledge_points

Revision ID: d44e178bf6be
Revises: a9e4ba5cc625
Create Date: 2026-03-09 21:44:07.001996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44e178bf6be'
down_revision: Union[str, None] = 'a9e4ba5cc625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_name'), 'knowledge_points', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_points_parent_id'), 'knowledge_points', ['parent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_status'), 'knowledge_points', ['status'], unique=False)
    op.create_table('knowledge_point_relations',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'relation_type')
    )
    op.create_table('knowledge_point_candidates',
    sa.Column('document_chunk_id', sa.UUID(), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_description', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_point_candidates_document_chunk_id'), 'knowledge_point_candidates', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_point_candidates_status'), 'knowledge_point_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_point_candidates_status'), table_name='knowledge_point_candidates')
    op.drop_index(op.f('ix_knowledge_point_candidates_document_chunk_id'), table_name='knowledge_point_candidates')
    op.drop_table('knowledge_point_candidates')
    op.drop_table('knowledge_point_relations')
    op.drop_index(op.f('ix_knowledge_points_status'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_parent_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_name'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
